name: Generate Changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install conventional-changelog-cli
        run: npm install -g conventional-changelog-cli

      - name: Generate CHANGELOG.md
        run: conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Commit & Push Changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG"
          git push origin HEAD:master
